default:
  image: gumjoe/wacc-ci-scala:x86

stages:
  - build
  - test

build:
  stage: build
  script:
    - scala compile .


frontend-test:
  stage: test
  dependencies:
    - build
  script:
    - scala test . -- -u reports -n wacc.Frontend
  artifacts:
    when: always
    paths:
      - reports/
    reports:
      junit: reports/*.xml

backend-test:
  stage: test
  dependencies:
    - build
  script:
    - scala test . -- -u reports -n wacc.Backend
  artifacts:
    when: always
    paths:
      - reports/
    reports:
      junit: reports/*.xml
