default:
  image: gumjoe/wacc-ci-scala:x86

stages:
  - build
  - style
  - test

build:
  stage: build
  script:
    - scala compile .

style:
  stage: style
  dependencies:
    - build
  script:
    - scalafmt --test .
  allow_failure: true

frontend-test:
  stage: test
  dependencies:
    - build
  script:
    - scala test . -- -u reports -n wacc.Frontend
  artifacts:
    when: always
    paths:
      - reports/
    reports:
      junit: reports/*.xml

backend-test:
  stage: test
  dependencies:
    - build
  script:
    - scala test . -- -u reports -n wacc.Backend
  artifacts:
    when: always
    paths:
      - reports/
    reports:
      junit: reports/*.xml

imports-test:
  stage: test
  dependencies:
    - build
  script:
    - scala test . -- -u reports -n wacc.Imports
  artifacts:
    when: always
    paths:
      - reports/
    reports:
      junit: reports/*.xml

